# Generated by Django 4.1.3 on 2022-11-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=1024)),
            ],
        ),
    ]
