# Generated by Django 4.1.3 on 2022-11-03 03:10

from django.db import migrations, models
import django.db.models.deletion
import organizations.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_address_alter_organization_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', organizations.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organizations.organization'),
        ),
    ]
